# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1048, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 80, 211, 91))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.text_to_insert = QtWidgets.QTextEdit(self.centralwidget)
        self.text_to_insert.setGeometry(QtCore.QRect(130, 190, 211, 51))
        self.text_to_insert.setObjectName("text_to_insert")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 150, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.add_btn = QtWidgets.QPushButton(self.centralwidget)
        self.add_btn.setGeometry(QtCore.QRect(190, 250, 75, 23))
        self.add_btn.setObjectName("add_btn")
        self.toDoListTable = QtWidgets.QTableWidget(self.centralwidget)
        self.toDoListTable.setGeometry(QtCore.QRect(420, 160, 391, 251))
        self.toDoListTable.setObjectName("toDoListTable")
        self.toDoListTable.setColumnCount(3)
        self.toDoListTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.toDoListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.toDoListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.toDoListTable.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1048, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionArchived = QtWidgets.QAction(MainWindow)
        self.actionArchived.setObjectName("actionArchived")
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionArchived)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Jethro\'s To Do List App"))
        self.label_2.setText(_translate("MainWindow", "Add Item"))
        self.add_btn.setText(_translate("MainWindow", "Add"))
        item = self.toDoListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.toDoListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Added"))
        item = self.toDoListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Completed"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionArchived.setText(_translate("MainWindow", "Archived"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
